# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  buildConfiguration: 'Release'
  serviceConnection : 'sc-azure'
  artifactName: 'drop'
  environment: 'dev'
  webAppName: 'webapp-h22-dev-122'


stages:
- stage : 'Build'
  displayName: 'Build et execution des tests'
  jobs:
  - template: pipelines/templates/build-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      artifactName: $(artifactName)


- stage : 'DeployToDevPostulations' 
  displayName: 'Déploiment en Dev'
  dependsOn: 'Build'
  jobs:
  - template: pipelines/templates/deploy-template.yml
    parameters:
      environment: 'dev'
      artifactName: $(artifactName)
      package: 'ModernRecrut.Postulation.API.zip'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-postulation-to6vosiht4kea'