# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  serviceConnection: 'sc-azure'
  appName: 'az-webapp-docker'
  containerRegistry: 'acrtp3q4.azurecr.io'
  acrServiceConnection: 'sc-acr'
  imageRepository: 'emploiapi'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: 'Build'
  displayName: 'Generation et push image'
  pool:
    vmImage: 'ubuntu-lastet'
  jobs:
  - job: 'Build'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '$(acrServiceConnection)'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '$(dockerfilePath)'
        buildContext: '$(Build.SourceDirectory)'
      displayName: 'Génération et push image dans registre de conteneurs'



#pool:
#  vmImage: ubuntu-latest

#steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
