# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
  serviceConnection: 'sc-azure'
  containerRegistry: 'acrtp3q4.azurecr.io'
  acrServiceConnection: 'sc-container-registry'
  imageRepository: 'emploiapirepositoy'
  dockerfilePath: '**/Dockerfile'
  ressourceGroup: "rg-tp3-q4"
  containerName: "emploiapicontainer"
  tag: '$(Build.BuildId)'

stages:
- stage: 'Build'
  displayName: 'Generation et push image'
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: 'Build'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: '$(acrServiceConnection)'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: '$(dockerfilePath)'
        buildContext: '$(Build.SourcesDirectory)'
      displayName: 'Génération et push image dans registre de conteneurs'

- stage: 'Deploy'
  displayName: 'Déploiement vers Azure Container Instances'
  variables:
    username: 'acrtp3q4'
  jobs:
  - job: 'Deploy'
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: '$(serviceConnection)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Récupérer les informations de l'image depuis le registre de conteneurs
          imageUri=$(az acr repository show-tags --name $(containerRegistry) --repository $(imageRepository) --output tsv --query '[0].tags[0]')
          
          # Créer un groupe de ressources pour ACI
          #az group create --name MyResourceGroup --location eastus

          # Créer un conteneur à partir de l'image
          #az container create --resource-group $(ressourceGroup) --name $(containerName) --image $imageUri --cpu 1 --memory 1.5Gi --registry-login-server $(containerRegistry) --registry-username $(username) --registry-password $(PASSWORD)
          az container create --resource-group $(ressourceGroup) --name $(containerName) --image $(containerRegistry)/$(imageRepository):$(tag) --cpu 1 --memory 1Gi --registry-login-server $(containerRegistry) --registry-username $(username) --registry-password $(PASSWORD)

          # Afficher l'adresse IP publique du conteneur
          #az container show --resource-group MyResourceGroup --name mycontainer --query ipAddress.ip --output tsv
    displayName: 'Déploiement vers Azure Container Instances'

#pool:
#  vmImage: ubuntu-latest

#steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'
