# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  buildConfiguration: 'Release'
  serviceConnection : 'sc-azure'
  artifactName: 'drop'

stages:
- stage : 'Build'
  displayName: 'Build et execution des tests'
  jobs:
  - template: pipelines/templates/build-template.yml
    parameters:
      buildConfiguration: $(buildConfiguration)
      artifactName: $(artifactName)

## Deploiement en Dev
- stage : 'DeployToDevDocuments' 
  displayName: 'Déploiement en Dev API Documents'
  dependsOn: 'Build'
  jobs:
  - template: pipelines/templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: $(artifactName)
      packageName: 'ModernRecrut.Documents.API.zip'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-documents-to6vosiht4kea'

- stage : 'DeployToDevEmplois' 
  displayName: 'Déploiement en Dev API Emplois'
  dependsOn: 'Build'
  jobs:
  - template: pipelines/templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: $(artifactName)
      packageName: 'ModernRecrut.Emplois.API.zip'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-emplois-to6vosiht4kea'

- stage : 'DeployToDevFavoris' 
  displayName: 'Déploiement en Dev API Favoris'
  dependsOn: 'Build'
  jobs:
  - template: pipelines/templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: $(artifactName)
      packageName: 'ModernRecrut.Favoris.API.zip'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-favoris-to6vosiht4kea'


- stage : 'DeployToDevPostulations' 
  displayName: 'Déploiement en Dev API Postulations'
  dependsOn: 'Build'
  jobs:
  - template: pipelines/templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: $(artifactName)
      packageName: 'ModernRecrut.Postulation.API.zip'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-postulation-to6vosiht4kea'

- stage : 'DeployToDevMVC' 
  displayName: 'Déploiement en Dev MVC'
  dependsOn:
    - 'Build'
    - 'DeployToDevDocuments'
    - 'DeployToDevEmplois'
    - 'DeployToDevFavoris'
    - 'DeployToDevPostulations'
  jobs:
  - template: pipelines/templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: $(artifactName)
      packageName: 'ModernRecrut.MVC.zip'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-mvc-to6vosiht4kea'

## Deploiement en Production
- stage : 'DeployToProductionDocuments' 
  displayName: 'Déploiement en Production API Documents'
  dependsOn: 'DeployToDevMVC'
  jobs:
  - template: pipelines/templates/deploy-template.yml
    parameters:
      environment: 'Production'
      artifactName: $(artifactName)
      packageName: 'ModernRecrut.Documents.API.zip'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-documents-cbw7hsdswfm44'

- stage : 'DeployToProductionEmplois' 
  displayName: 'Déploiement en Production API Emplois'
  dependsOn: 'DeployToDevMVC'
  jobs:
  - template: pipelines/templates/deploy-template.yml
    parameters:
      environment: 'Production'
      artifactName: $(artifactName)
      packageName: 'ModernRecrut.Emplois.API.zip'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-emplois-cbw7hsdswfm44'

- stage : 'DeployToProductionFavoris' 
  displayName: 'Déploiement en Production API Favoris'
  dependsOn: 'DeployToDevMVC'
  jobs:
  - template: pipelines/templates/deploy-template.yml
    parameters:
      environment: 'Production'
      artifactName: $(artifactName)
      packageName: 'ModernRecrut.Favoris.API.zip'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-favoris-cbw7hsdswfm44'


- stage : 'DeployToProductionPostulations' 
  displayName: 'Déploiement en Production API Postulations'
  dependsOn: 'DeployToDevMVC'
  jobs:
  - template: pipelines/templates/deploy-template.yml
    parameters:
      environment: 'Production'
      artifactName: $(artifactName)
      packageName: 'ModernRecrut.Postulation.API.zip'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-postulation-cbw7hsdswfm44'

- stage : 'DeployToProductionMVC' 
  displayName: 'Déploiement en Production MVC'
  dependsOn:
    - 'DeployToDevMVC'
    - 'DeployToProductionDocuments'
    - 'DeployToProductionEmplois'
    - 'DeployToProductionFavoris'
    - 'DeployToProductionPostulations'
  jobs:
  - template: pipelines/templates/deploy-template.yml
    parameters:
      environment: 'Production'
      artifactName: $(artifactName)
      packageName: 'ModernRecrut.MVC.zip'
      serviceConnection: $(serviceConnection)
      webAppName: 'webapp-mvc-cbw7hsdswfm44'