parameters:
  environementIAC: 'dev'
  location: 'canadacentral'
  resourceGroupName: '' # Fournir le nom du groupe de ressources lors de l'utilisation du modèle
  serviceConnection: '' # Fournir la connexion de service Azure DevOps lors de l'utilisation du modèle
  templateFile: '**/main.bicep'
  webAppName: 'webapp-${{ parameters.environementIAC }}-fgsdfg'

jobs:
- job: 
  pool:
    vmImage: ubuntu-latest

  steps:
  - task: AzureCLI@2
    displayName: 'Environement ${{ parameters.environementIAC }}'
    inputs:
      azureSubscription: ${{ parameters.serviceConnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az --version
        az group create --name ${{ parameters.resourceGroupName }} --location ${{ parameters.location }}
        az deployment group create --resource-group ${{ parameters.resourceGroupName }} --template-file ${{ parameters.templateFile }} --parameters appName=${{ parameters.webAppName }}
