# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - bicep

pool:
  vmImage: ubuntu-latest

variables:
  location: 'canadacentral'
  templateFile: '**/main.bicep'
  serviceConnection: 'sc-azure'

stages:
- stage: 'IacDev'
  jobs:
  - deployment: 'DeployToDev'
    environment: 'Dev'
  - job: 'Deployment'
    variables:
      resourceGroupName: 'rg-dev-tp3'
    steps:
    - task: AzureCLI@2
      displayName: 'Environement Dev'
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az --version
          az group create --name $(resourceGroupName) --location $(location)
          az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile)

- stage: 'IacProd'
  jobs:
  - deployment: 'DeployToProduction'
    environment: 'Production'
  - job: 'Deployment'
    variables:
      resourceGroupName: 'rg-prod-tp3'
    steps:
    - task: AzureCLI@2
      displayName: 'Environement Production'
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az --version
          az group create --name $(resourceGroupName) --location $(location)
          az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile)

##### Environnement !!!
#stages:
#- stage: 'IacDev'
#  displayName: 'Deploy the Dev Iac'
#  jobs:
#    - deployment: Deploy
#      
#      pool:
#        vmImage: 'ubuntu-20.04'
#      environment: dev
#      variables:
#        resourceGroupName: 'rg-dev-tp3-test'
#        templateFile: '**/main.bicep'
#      strategy:
#        runOnce:
#          deploy:
#            steps:
#            - task: AzureCLI@2
#              displayName: 'Environement Dev'
#              inputs:
#                azureSubscription: $(serviceConnection)
#                scriptType: bash
#                scriptLocation: inlineScript
#                inlineScript: |
#                  az --version
#                  az group create --name $(resourceGroupName) --location $(location)
#                  az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile)
