# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - bicep

pool:
  vmImage: ubuntu-latest

variables:
  location: 'canadacentral'
  templateFile: '**/main.bicep'
  serviceConnection: 'sc-azure'

stages:
- stage: 'IacDev'
  jobs:
    - job: 'Deployment'
      variables:
        resourceGroupName: 'rg-dev-tp3'
        #webAppName: 'app-dev-recrut-123'
      steps:
      - task: AzureCLI@2
        displayName: 'Environement Dev'
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az --version
            az group create --name $(resourceGroupName) --location $(location)
            az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile)

- stage: 'IacProd'
  jobs:
    - job: 'Deployment'
      variables:
        resourceGroupName: 'rg-prod-tp3'
      steps:
      - task: AzureCLI@2
        displayName: 'Environement Prod'
        inputs:
          azureSubscription: $(serviceConnection)
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            az --version
            az group create --name $(resourceGroupName) --location $(location)
            az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile)