# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

## Execution du pipelines si le fichier est modifier ou si fichier bicep/infra est modifier
trigger:
  - none
  ##branches:
  ##  include:
  ##    - bicep/infra


pool:
  vmImage: ubuntu-latest

variables:
  serviceConnection: 'az-serviceprincipal'
  resourceGroupName: 'rg-test-devops'
  location: 'canadacentral'
  templateFile: '**/main.bicep'
  webAppName: 'webapp-dev-3213123'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(serviceConnection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az group create --name $(ressourceGroupName) --location $(location)
      az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile)
      parameters webAppName=$(webAppName)
