# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - bicep

stages:
- stage: 'Dev'
  displayName: 'IAC Dev'
  jobs:
  - template: pipelines/templates/iac-azure-template-pipelines.yml
    parameters:
      environementIAC: 'dev'
      resourceGroupName: 'rg-test-devops'
      serviceConnection: 'az-serviceprincipal' 

#pool:
#  vmImage: ubuntu-latest

#variables:
#  serviceConnection : 'az-serviceprincipal'
#  resourceGroupName: 'rg-test-devops'
#  location: 'canadacentral'
#  templateFile: '**/main.bicep'
#  webAppName: 'webapp-dev-fdafadafsfd'

#steps:
#  - task: AzureCLI@2
#    displayName: 'Environement Dev'
#    inputs:
#      azureSubscription: $(serviceConnection)
#      scriptType: bash
#      scriptLocation: inlineScript
#      inlineScript: |
#        az --version
#        az group create --name $(resourceGroupName) --location $(location)
#        az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) --parameters appName=$(webAppName)
